name: 发布软件

on:
  workflow_dispatch: # 手动触发

permissions: write-all # 给所有工作写权限

jobs:
  jobs_window:
    name: 构建window软件
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 编译环境设置 Python 3.9.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.13"
          architecture: "x64"
      - name: 缓存加载
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('**/requirements.txt') }}
      - name: 安装依赖
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt
      - name: 编译exe
        run: pyinstaller -F main.py
      - name: 上传exe
        uses: actions/upload-artifact@v3
        with:
          name: window
          path: ./dist/*.exe

  jobs4:
    needs: jobs_window
    name: 发布版本
    runs-on: ubuntu-latest
    steps:
      - name: 下载产物
        id: download
        uses: actions/download-artifact@v3
        with:
          path: ./
      - name: 读入环境信息
        run: |
          echo ${{steps.download.outputs.download-path}}
          ls -R
      - name: 发布文件
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true # 覆盖文件
          tag: "auto"
          body: |
            - Github Actions自动打包
            - hdd.cm 推特低至2毛
          artifacts: "window/*.exe"
